#!/usr/bin/env bash
# Bash script that displays "Valentine Kiguli" 10 times and "Hi" in 9th iteration times

cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 9 ]
    then
echo "Hello"
    fi
    echo "Valentine Kiguli"
    let cont=cont+1
done